//-----------------------------------------------------------------------------
// Copyright 2023, Ed Keenan, all rights reserved.
//----------------------------------------------------------------------------- 

#include "Vec4_Add_Vec4.cpp"                                                            
#include "Vec4_Assignment_Operator.cpp"                                      
#include "Vec4_ConstantCheck.cpp"                                                  
#include "Vec4_Constructor_Copy.cpp"                  
#include "Vec4_Constructor_Default.cpp"                                         
#include "Vec4_Constructor_Individual.cpp"                                
#include "Vec4_Constructor_Vec3.cpp"                  
#include "Vec4_Destructor.cpp"                                                        
#include "Vec4_Dot.cpp"                                                                      
#include "Vec4_Get_Accessors.cpp"                                                  
#include "Vec4_Get_Accessors_const.cpp"                                      
#include "Vec4_Get_Brackets.cpp"                                                    
#include "Vec4_Get_Brackets_const.cpp"                                        
#include "Vec4_Get_Normalize.cpp"                                                  
#include "Vec4_IsEqualFalse.cpp"                                                    
#include "Vec4_IsEqualFalse_default.cpp"                                    
#include "Vec4_IsEqualTrue.cpp"                                                      
#include "Vec4_IsEqualTrue_default.cpp"                                      
#include "Vec4_IsZeroFalse.cpp"                                                      
#include "Vec4_IsZeroFalse_default.cpp"                                      
#include "Vec4_IsZeroTrue_default.cpp"                                        
#include "Vec4_IsZeroTrue_True.cpp"                                              
#include "Vec4_Len.cpp"                                                                      
#include "Vec4_MultEqual_Mat4.cpp"                                                
#include "Vec4_Mult_Mat4.cpp"                                                          
#include "Vec4_Mult_Scale.cpp"                                                        
#include "Vec4_Normalize.cpp"                                                          
#include "Vec4_PlusEqual_Vec4.cpp"                                                
#include "Vec4_Proxy.cpp"                                                                  
#include "Vec4_SampleTest.cpp"                                                        
#include "Vec4_ScaleEquals.cpp"                                                      
#include "Vec4_Scale_Vec4.cpp"                                                        
#include "Vec4_Set_4_Elements.cpp"                                                
#include "Vec4_Set_Accessors.cpp"                                                  
#include "Vec4_Set_Accessors_Get.cpp"                                          
#include "Vec4_Set_Brackets.cpp"                                                   
#include "Vec4_Set_Brackets_get.cpp"                                            
#include "Vec4_Set_Vec3.cpp"                                                            
#include "Vec4_Set_Vec4.cpp"                                                            
#include "Vec4_SubEqual_Vec4.cpp"                                                  
#include "Vec4_Sub_Vec4.cpp"                                                            
#include "Vec4_Unary_equal_Minus.cpp"                                          
#include "Vec4_Unary_equal_Plus.cpp"                                            
#include "Vec4_Unary_Minus.cpp"                                                      
#include "Vec4_Unary_Plus.cpp"                                                        


// ---  End of File ---------------
